export { default as XIcon } from "./x.svg";
export { default as GithubIcon } from "./github.svg";
export { default as GithubNavIcon } from "./github_nav.svg";
export { default as OpenSourceIcon } from "./opensource.svg";
export { default as OSIcon } from "./oss.svg";
export { default as StarIcon } from "./star.svg";
export { default as CopyIcon } from "./copy.svg";
export { default as CopySuccessIcon } from "./copy_success.svg";
export { default as SingleCommitIcon } from "./single_commit.svg";
